# Generated by Django 4.1.4 on 2022-12-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cours', '0003_alter_cours_auteur'),
        ('favoriteCours', '0002_alter_favoritecours_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecours',
            name='date',
        ),
        migrations.AlterField(
            model_name='favoritecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cours.cours'),
        ),
        migrations.AlterField(
            model_name='favoritecours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
