# Generated by Django 4.1.4 on 2022-12-26 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteCours', '0003_remove_favoritecours_date_alter_favoritecours_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecours',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
