# Generated by Django 4.1.4 on 2022-12-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitiude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('catégorie', models.CharField(choices=[('Primaire', 'Primaire'), ('College', 'College'), ('Lycée', 'Lycee')], max_length=20, null=True)),
                ('modalité', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('titre', models.CharField(max_length=100, null=True)),
                ('tarif', models.IntegerField(null=True)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lieuFormation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cours.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cours.cours')),
            ],
        ),
    ]
