# Generated by Django 4.1.4 on 2022-12-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cours.module'),
        ),
    ]
