# Generated by Django 4.1.4 on 2023-01-26 14:22

import Cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0005_alter_cours_catégorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Cours.models.upload_to),
        ),
    ]
