# Generated by Django 4.1.4 on 2023-01-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0006_alter_cours_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='tarifPromotion',
            field=models.IntegerField(null=True),
        ),
    ]
