# Generated by Django 4.1.4 on 2023-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0007_cours_tarifpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='modalité',
            field=models.CharField(choices=[('Online', 'Online'), ('Presental', 'Presental')], max_length=20, null=True),
        ),
    ]
