# Generated by Django 4.1.5 on 2023-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0010_rename_catégorie_cours_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='adresse',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='commune',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='wilaya',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
