# Generated by Django 4.1.5 on 2023-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0011_remove_cours_thumbnail_adresse_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='thumnail_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
