# Generated by Django 4.1.5 on 2023-01-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0011_remove_cours_thumbnail_adresse_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
