# Generated by Django 4.1.5 on 2023-01-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0012_alter_module_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
