# Generated by Django 4.1.5 on 2023-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_nometablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
